ReactiveCocoa/ReactiveObjC

- ReactiveObjC.podspec
Please, review & merge to master.
In this PR fix for CocoaPods compatibility with Mantle,
which also use `metamacros`.
> Fix linking error conflict with Mantle.

- ReactiveObjC/RACSubscriber.h
In general, it seems helpful to have nullability annotations specified within `RACSubscriber.h`, though perhaps there's a strong reason for which this file hasn't already been annotated that I'm not aware of.
However, according to [SE-0140](https://github.com/apple/swift-evolution/blob/master/proposals/0140-bridge-optional-to-nsnull.md):
> when an Optional is intentionally passed into Objective-C as a nonnull object, we should bridge some value by bridging the wrapped value, and bridge nones to a singleton such as NSNull
With SE-0140, which has already been implemented in Swift 3.0.1 (available in the Xcode 8.1 beta 3), it is important that nullability annotations be specified on `RACSubscriber`. Otherwise, when `RACSubscriber.sendNext()` is passed an `Optional.none` from within Swift, …
> Add nullability annotations to RACSubscriber

- ReactiveObjC/RACCommand.h
- ReactiveObjC/RACCommand.m
- ReactiveObjC/RACEvent.h
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSignal+Operations.m
- ReactiveObjC/RACSignal.h
For many `RACSignal` operators, the `ValueType` of signals will not change due to operator being invoked. As such, in these cases, lightweight generics can be added to improve the type signature of the return value.
This additionally adds lightweight generics to `RACEvent` so that it can maintain the `ValueType` of the `RACSignal` events that is is representing via the `materialize` operator.
Finally, in some places (such as class methods on `RACSignal`, the return type has been updated to be `RACSignal<ValueType> *`. This is to allow the following style of declaration in Swift:
```
let signal = RACSignal<NSNumber>.createSignal { subscriber…
```
This follows the pattern of Apple’s generics, e.g. `+[NSArray (nullable NSMutableArray<ObjectType> *)arrayWithContentsOfFile:(NSString *)path]`
> Add lightweight generics to signal operations where applicable

- ReactiveObjC/RACSignal.h
Since the operations built on `RACStream` primitives have an `instancetype` return value, the compiler assumes that they inherit the receiving signal’s `ValueType` when they are invoked on `RACSignal`. For operators like `map:`, this is almost always an incorrect assumption. As such, in cases where the `ValueType` of the result of the operation is not able to be inferred, the `ValueType` is erased in the result by returning `RACSignal *` with no `ValueType` information.
Additionally, in cases where `instancetype` is a valid return type and no more precise `ValueType` information could be added to the method signature, the operation is not redeclared, since the compiler will assume the correct return types.
Finally, in cases where more precise type information could be provided, the …
> Redeclare operations from RACStream with more precise ValueType

- ReactiveObjC/RACStream.m
Fixes the warning emitted by the static analyzer:
> Null is returned from a method that is expected to return a non-null value
This change should not be an issue in practice because consumers should not be invoking methods on `RACStream` directly, as it is an abstract base class.
> Fix static analyzer warnings

- ReactiveObjC.xcodeproj/project.pbxproj
- ReactiveObjC/RACArraySequence.h
- ReactiveObjC/RACArraySequence.m
- ReactiveObjC/RACEagerSequence.m
- ReactiveObjC/RACEmptySequence.h
- ReactiveObjC/RACIndexSetSequence.h
- ReactiveObjC/RACIndexSetSequence.m
- ReactiveObjC/RACSequence.h
- ReactiveObjC/RACSequence.m
- ReactiveObjC/RACSignal.h
- ReactiveObjC/RACSignal.m
- ReactiveObjC/RACStream+Private.h
- ReactiveObjC/RACStream.h
- ReactiveObjC/RACStream.m
- ReactiveObjC/RACTupleSequence.h
- ReactiveObjC/RACTupleSequence.m
- ReactiveObjC/RACUnarySequence.h
- ReactiveObjC/RACUnarySequence.m
Redeclares operations built on RACStream primitives with more precise type information. This continues the work from #37 by adding the RACStream operators RACSequence, and updating RACStream methods to return `__kindof RACStream`.
This will allow lightweight generics to be added to `RACSequence` quite easily (following the same pattern as RACSignal), if desired.
I have verified that this fixes issue #40 by testing out the code in the issue. This is fixed by giving less precise type information to the `RACSteam` operator return values (`__kindof RACStream *`, rather than `instancetype`, as before), so that the compiler references the `RACSignal` version.
Additionally, I have verified that our large ReactiveCocoa 2.x codebase can be successfully migrated with these changes without any other …
> Redeclare operations built on RACStream primitives with more precise type information (continued)

- ReactiveObjC/NSArray+RACSequenceAdditions.h
- ReactiveObjC/NSDictionary+RACSequenceAdditions.h
- ReactiveObjC/NSEnumerator+RACSequenceAdditions.h
- ReactiveObjC/NSIndexSet+RACSequenceAdditions.h
- ReactiveObjC/NSOrderedSet+RACSequenceAdditions.h
- ReactiveObjC/NSSet+RACSequenceAdditions.h
- ReactiveObjC/NSString+RACSequenceAdditions.h
- ReactiveObjC/RACDynamicSequence.m
- ReactiveObjC/RACSequence.h
- ReactiveObjC/RACSequence.m
- ReactiveObjC/RACSignal+Operations.h
Continues the pattern established with RACSignal into RACSequence by adding `__coviariant ValueType` lightweight generics.
> Add ValueType lightweight generic to RACSequence

- ReactiveObjC.podspec
- ReactiveObjC/Info.plist
- ReactiveObjCTests/Info.plist
This is to make a release that https://github.com/ReactiveCocoa/ReactiveObjCBridge/pull/6 will be able to consume.
I think it would make sense to merge ~#34~, ~#37~, ~#41~, and ~#42~ before making this release.
> Update version to 2.1

- ReactiveObjC/RACSignal+Operations.h
This was missed in the review of #35, see https://github.com/ReactiveCocoa/ReactiveObjC/pull/35#discussion_r88453516
> Annotate RACSignal if:then:else: generic

- ReactiveObjC/RACSignal+Operations.h
Unless buffer's functionality has changed, it should be sending along `RACTuple`s of `ValueType`, not `ValueType` itself.
> Fix bufferWithTime return value

- ReactiveObjC/RACSequence.h
This method was missed during the initial `RACSequence` migration.
> Annotate ValueType on objectPassingTest:

- ReactiveObjC/extobjc/metamacros.h
It is not necessary to use the header guard because `#import` will ensure that the header is included at most once.
It also causes `metamacro_xxx not found error` when ReactiveObjC is imported by `@import ReactiveObjC`. I don't understand how objc modules work, so I cannot explain why it causes such errors.
> remove the unecessary header guard

- ReactiveObjC/RACStream.h
Fixes #70
Swift is unable to disambiguate between methods declared both on a non-generic base class and a generic subclass.
> Annotate ValueType on RACStream

- Documentation/DesignGuidelines.md
This guideline encourages the use of `-rac_liftSelector:withSignals:` to
effect implicit subscription. However, the eager subscription that
occurs when that method is called [is regarded as a mistake][0],
and [its use to effect implicit subscription is discouraged][1].
[0]: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1096#issuecomment-34506990
[1]: https://github.com/ReactiveCocoa/ReactiveCocoa/issues/1096#issuecomment-34842565
> Don't encourage `-rac_liftSelector:withSignals:` for subscription

- ReactiveObjC/NSObject+RACLifting.h
As an example, this allows us to change the following Swift code:
```swift
self.rac_liftSelector(mySelector, withSignalOfArguments: mySignalOfTuples as! RACSignal<AnyObject>)
```
into this:
```swift
self.rac_liftSelector(mySelector, withSignalOfArguments: mySignalOfTuples)
```
> Add type annotations for NSObject+RACLifting

- ReactiveObjC/RACBehaviorSubject.h
- ReactiveObjC/RACBehaviorSubject.m
- ReactiveObjC/RACEmptySignal.h
- ReactiveObjC/RACEmptySignal.m
- ReactiveObjC/RACErrorSignal.h
- ReactiveObjC/RACMulticastConnection+Private.h
- ReactiveObjC/RACMulticastConnection.h
- ReactiveObjC/RACReturnSignal.h
- ReactiveObjC/RACSignal+Operations.h
This pull request adds generics to `RACMulticastConnection`, `RACBehaviorSubject` and type annotations to `RACSignal`'s `+empty` and `+return` methods.
It seems to me that it'd also make sense to add generics to `RACChannelTerminal`, `RACChannel` and `RACSubject`. Thoughts on that?
> More type annotations

- ReactiveObjC/RACSignal+Operations.h
These were missed during the initial generics conversion.
> Improve missing or imprecise RACSignal type annotations

- ReactiveObjC.xcodeproj/project.pbxproj
- ReactiveObjC/RACAnnotations.h
- ReactiveObjC/RACMulticastConnection.h
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSignal.h
One of the most common sources of confusion with developers that are new to the concepts of FRP is that subscriptions are required to drive values through signal operators. New developers frequently spend a long time trying to figure out why code such as:
```
[signal logAll];
```
is not performing any logging side-effects. To help with this confusion, I’ve added unused result warnings to side-effectless signal operators to help raise a warning to newcomers that operators are side-effectless.
This change will also help with catching typos that would otherwise compile without warning, such as forgetting to type `return` before a signal chain when you are attempting to write an early return in a method.
> Add warnings to unused signal operator results

- ReactiveObjC/RACBehaviorSubject.h
- ReactiveObjC/RACBehaviorSubject.m
- ReactiveObjC/RACEmptySignal.h
- ReactiveObjC/RACMulticastConnection+Private.h
- ReactiveObjC/RACReplaySubject.h
- ReactiveObjC/RACReturnSignal.h
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSubject.h
Lightweight generics for RACSubject, giving us some autocompletion and helping us bridge with Swift.
Solves #58.
Unfortunately I couldn't find a nice way of extending the generics to `sendNext:`, for the reason that ObjC protocols don't support generics (`sendNext:` is declared in `RACSubscriber`).
> RACSubject generics

- ReactiveObjC/RACChannel.h
- ReactiveObjC/RACChannel.m
- ReactiveObjC/RACKVOChannel.h
- ReactiveObjC/UIControl+RACSignalSupportPrivate.h
- ReactiveObjC/UIDatePicker+RACSignalSupport.h
- ReactiveObjC/UISegmentedControl+RACSignalSupport.h
- ReactiveObjC/UISlider+RACSignalSupport.h
- ReactiveObjC/UIStepper+RACSignalSupport.h
- ReactiveObjC/UISwitch+RACSignalSupport.h
- ReactiveObjC/UITextField+RACSignalSupport.h
Both of them now have exactly one associated value (a covariant).
> Add lightweight generics to RACChannel and RACChannelTerminal.

- ReactiveObjC/NSDictionary+RACSequenceAdditions.h
- ReactiveObjC/NSObject+RACPropertySubscribing.h
- ReactiveObjC/NSObject+RACSelectorSignal.h
- ReactiveObjC/NSURLConnection+RACSupport.h
- ReactiveObjC/RACSequence.h
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSignal.h
- ReactiveObjC/RACTuple.h
- ReactiveObjC/RACTuple.m
- ReactiveObjCTests/RACPropertySignalExamples.m
- ReactiveObjCTests/RACTupleSpec.m
This change adds lightweight generic typed tuples as subclasses of `RACTuple`. This allows tuples to be annotated with the types that they contain, e.g. `RACTwoTuple<NSNumber *, NSString *>`. The supported counts are 1: `RACOneTuple`, 2: `RACTwoTuple`, 3: `RACThreeTuple`, 4: `RACFourTuple`, and 5: `RACFiveTuple`.
To attempt to best satisfy the compiler, `RACTuplePack()` was updated to produce the correct `RACTuple` subclass depending on the number of arguments it is provided. In most cases from now on, if you have a tuple with two elements, you will have a `RACTwoTuple` (and so on). However, you can still produce a regular `RACTuple` with two, three, four, or five elements by using the explicit initialization methods (e.g. `RACTuple tupleWithObjectsFromArray:`).
In cases where you have a …
> Add generic typed tuples

- ReactiveObjC.podspec
- ReactiveObjC/Info.plist
- ReactiveObjCTests/Info.plist
Includes #75, #80, #81, #82, #83, #85, #87, and #88.
While this has no breaking changes in Obj-C, it will likely introduce breaking changes in Swift. See #90.
> Increase version to 3.0.0

- ReactiveObjC/RACTuple.h
`RACOneTuple` and `RACTwoTuple` were missing the `nullable` annotations in their `+pack` methods.
> Add missing nullable annotation for RACOneTuple and RACTwoTuple

- ReactiveObjC/RACSignal.h
- ReactiveObjC/RACSignal.m
This resolves https://github.com/ReactiveCocoa/ReactiveObjC/issues/95
> Add async wait methods that support custom timeout

- ReactiveObjC/RACSequence.h
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSignal+Operations.m
- ReactiveObjC/RACSignal.h
- ReactiveObjC/RACStream.h
- ReactiveObjC/RACStream.m
- ReactiveObjC/extobjc/EXTScope.h
Resolves #115.
Preceded by #119 and #122.
> Xcode9 prototype issue fix

- ReactiveObjC/extobjc/EXTRuntimeExtensions.m
Xcode analyzer reports `Potential leak of memory pointed to by 'attributes'`. And also, sometimes Xcode can't find `EXTRuntimeExtensions.h`. This PR fixes these issues.
See also: The same PR is already merged into original `libextobjc` https://github.com/jspahrsummers/libextobjc/pull/141
> Fix memory leak of `attributes`

- .travis.yml
- Cartfile.resolved
- ReactiveObjC.xcodeproj/project.pbxproj
- ReactiveObjC/Deprecations+Removals.swift
- ReactiveObjC/NSObject+RACAppKitBindings.m
- ReactiveObjC/NSObject+RACKVOWrapper.m
- ReactiveObjC/NSObject+RACSelectorSignal.h
- ReactiveObjC/NSObject+RACSelectorSignal.m
- ReactiveObjC/RACBlockTrampoline.m
- ReactiveObjC/RACCommand.h
- ReactiveObjC/RACCommand.m
- ReactiveObjC/RACDisposable.m
- ReactiveObjC/RACSignal+Operations.h
- ReactiveObjC/RACSignal+Operations.m
- ReactiveObjCTests/RACSwiftBridgingSpec.swift
Redefines `RACSignalError` using `NS_ERROR_ENUM`, allowing it to bridge to Swift as a new `RACSignalError` struct containing static instances of `RACSignalError.Code`, and allowing it to be used in error pattern matching contexts.
> Support Swift bridging for RACSignalError using NS_ERROR_ENUM

- ReactiveObjC/RACReplaySubject.m
- ReactiveObjCTests/RACSubjectSpec.m
valuesReceived should be cleaned up before sending value.
If we have subscription and creating another subscription on the same RACReplaySubject while -take:1 it - we can get first value instead of second.
```
RACReplaySubject *subject = [RACReplaySubject replaySubjectWithCapacity:1];
[subject subscribeNext:^(id  _Nullable item1) {
NSLog(@"%@", item1);
[[subject take:1] subscribeNext:^(id  _Nullable item2) {
NSLog(@"%@", item2);
}];
}];
[subject sendNext:@"first"];
[subject sendNext:@"second"];
```
Expected:
> first
> first
> second
> second
Got:
> first
> first
> second
> first
> Update order of invocation in -sendNext: RACReplaySubject

- ReactiveObjC.podspec
Updates the Podspec for yesterdays 3.1.1 Release.
Someone will have to do the actual Cocoapod release as well.
> Update Podspec for 3.1.1
